#!/usr/bin/env bash
set -euo pipefail

##############################################################################
# publish_sections.sh
#
# Reconstruct a LaTeX document monotonically from a complete source file.
#
# The source remains uncommitted. The destination file is built incrementally:
#
#   1. Copy the preamble and front matter.
#   2. Commit it as the manuscript initialization.
#   3. Append each structural unit.
#   4. Classify the addition from its LaTeX and keywords.
#   5. Commit only the destination file.
#   6. Push once after all commits.
#
# Default files:
#
#   Source:       template.tex
#   Index:        template.index.tsv
#   Destination:  rsvp-evolution.tex
#
# Dry run:
#
#   ./publish_sections.sh --dry-run
#
# Real run:
#
#   ./publish_sections.sh
#
# Restart from the beginning:
#
#   ./publish_sections.sh --restart
#
# Publish at chapter rather than section granularity:
#
#   ./publish_sections.sh --level chapter
#
##############################################################################

SOURCE="template.tex"
INDEX="template.index.tsv"
OUTPUT="rsvp-evolution.tex"
LEVEL="section"

DRY_RUN=0
RESTART=0
NO_PUSH=0
COMPILE_CHECK=0

LOG=""
GIT_DIR=""
STATE_FILE=""

##############################################################################
# Help
##############################################################################

usage() {
    cat <<'EOF'
Usage:
  ./publish_sections.sh [options]

Options:
  --source FILE       Complete source LaTeX file
                      Default: template.tex

  --index FILE        TSV index generated by index_latex.sh
                      Default: template.index.tsv

  --output FILE       Destination reconstructed file
                      Default: rsvp-evolution.tex

  --level LEVEL       Finest structural unit to commit
                      Values:
                        part
                        chapter
                        section
                        subsection
                        subsubsection
                      Default: section

  --dry-run           Show every planned operation without changing files,
                      creating commits, writing state, or pushing

  --restart           Rebuild the destination from the beginning
                      Removes the destination and saved publishing state

  --no-push           Create commits but do not push at the end

  --compile-check     Run lualatex after each addition and stop on failure

  -h, --help          Show this help

Examples:
  ./publish_sections.sh --dry-run

  ./publish_sections.sh --restart --dry-run

  ./publish_sections.sh --restart

  ./publish_sections.sh --level chapter --dry-run

  ./publish_sections.sh \
      --source template.tex \
      --index template.index.tsv \
      --output rsvp-evolution.tex \
      --level section
EOF
}

##############################################################################
# Arguments
##############################################################################

while (($# > 0)); do
    case "$1" in
        --source)
            [[ $# -ge 2 ]] || {
                echo "ERROR: --source requires a filename." >&2
                exit 1
            }
            SOURCE="$2"
            shift 2
            ;;

        --index)
            [[ $# -ge 2 ]] || {
                echo "ERROR: --index requires a filename." >&2
                exit 1
            }
            INDEX="$2"
            shift 2
            ;;

        --output)
            [[ $# -ge 2 ]] || {
                echo "ERROR: --output requires a filename." >&2
                exit 1
            }
            OUTPUT="$2"
            shift 2
            ;;

        --level)
            [[ $# -ge 2 ]] || {
                echo "ERROR: --level requires a value." >&2
                exit 1
            }
            LEVEL="$2"
            shift 2
            ;;

        --dry-run)
            DRY_RUN=1
            shift
            ;;

        --restart)
            RESTART=1
            shift
            ;;

        --no-push)
            NO_PUSH=1
            shift
            ;;

        --compile-check)
            COMPILE_CHECK=1
            shift
            ;;

        -h|--help)
            usage
            exit 0
            ;;

        *)
            echo "ERROR: Unknown option: $1" >&2
            echo >&2
            usage >&2
            exit 1
            ;;
    esac
done

##############################################################################
# Validation
##############################################################################

case "$LEVEL" in
    part|chapter|section|subsection|subsubsection)
        ;;
    *)
        echo "ERROR: Unsupported level: $LEVEL" >&2
        echo "Use part, chapter, section, subsection, or subsubsection." >&2
        exit 1
        ;;
esac

[[ -f "$SOURCE" ]] || {
    echo "ERROR: Source file not found: $SOURCE" >&2
    exit 1
}

[[ -f "$INDEX" ]] || {
    echo "ERROR: Index file not found: $INDEX" >&2
    exit 1
}

git rev-parse --is-inside-work-tree >/dev/null 2>&1 || {
    echo "ERROR: Current directory is not inside a Git repository." >&2
    exit 1
}

GIT_DIR="$(git rev-parse --git-dir)"
STATE_FILE="$GIT_DIR/publish-$(basename "$OUTPUT").state"

if [[ "$DRY_RUN" == "0" ]]; then
    LOG="publish-$(date +%Y%m%d-%H%M%S).log"
fi

##############################################################################
# Output helpers
##############################################################################

say() {
    if [[ "$DRY_RUN" == "1" ]]; then
        printf '%s\n' "$*"
    else
        printf '%s\n' "$*" | tee -a "$LOG"
    fi
}

run_logged() {
    if [[ "$DRY_RUN" == "1" ]]; then
        printf 'DRY RUN:'
        printf ' %q' "$@"
        printf '\n'
    else
        "$@" 2>&1 | tee -a "$LOG"
    fi
}

die() {
    say "ERROR: $*"
    exit 1
}

##############################################################################
# Structural hierarchy
##############################################################################

rank_for_type() {
    case "$1" in
        part)           echo 1 ;;
        chapter)        echo 2 ;;
        section)        echo 3 ;;
        subsection)     echo 4 ;;
        subsubsection)  echo 5 ;;

        # These are structural boundaries even though they are not levels.
        appendix)       echo 1 ;;
        bibliography)   echo 1 ;;

        # Formal environments are subordinate to all requested heading levels.
        definition|theorem|lemma|corollary|proposition|proof|example|remark)
                        echo 90 ;;

        figure|table)    echo 90 ;;

        *)              echo 99 ;;
    esac
}

LEVEL_RANK="$(rank_for_type "$LEVEL")"

##############################################################################
# Text cleanup
##############################################################################

trim() {
    local value="$1"

    value="${value//$'\r'/}"

    value="$(printf '%s' "$value" |
        sed 's/^[[:space:]]*//' |
        sed 's/[[:space:]]*$//')"

    printf '%s' "$value"
}

clean_title() {
    local title
    title="$(trim "$1")"

    title="$(printf '%s' "$title" |
        sed 's/\\textit{//g' |
        sed 's/\\textbf{//g' |
        sed 's/\\emph{//g' |
        sed 's/[{}]//g' |
        sed 's/[[:space:]]\+/ /g')"

    [[ -n "$title" ]] || title="Untitled addition"

    printf '%s' "$title"
}

##############################################################################
# Fast content classification
##############################################################################

classify_chunk() {
    local type="$1"
    local title="$2"
    local chunk="$3"
    local searchable

    searchable="$(
        {
            printf '%s\n' "$title"
            sed -n '1,250p' "$chunk"
        } | tr '[:upper:]' '[:lower:]'
    )"

    # Structural transitions take precedence.

    case "$type" in
        part)
            echo "part"
            return
            ;;

        chapter)
            echo "chapter"
            return
            ;;

        appendix)
            echo "appendix"
            return
            ;;

        bibliography)
            echo "bibliography"
            return
            ;;
    esac

    # Formal mathematical additions.

    if grep -Eq \
        '\\begin\{theorem\}|\\begin\{lemma\}|\\begin\{corollary\}|\\begin\{proposition\}' \
        "$chunk"; then
        echo "theorem"
        return
    fi

    if grep -Eq '\\begin\{proof\}' "$chunk"; then
        echo "proof"
        return
    fi

    if grep -Eq '\\begin\{definition\}' "$chunk"; then
        echo "definition"
        return
    fi

    if grep -Eq \
        '\\begin\{equation\}|\\begin\{align\}|\\begin\{align\*\}|\\\[' \
        "$chunk"; then
        echo "formalism"
        return
    fi

    # Figures, tables, and computational content.

    if grep -Eq '\\begin\{figure\}|\\includegraphics' "$chunk"; then
        echo "figure"
        return
    fi

    if grep -Eq \
        '\\begin\{table\}|\\begin\{tabular\}|\\begin\{longtable\}' \
        "$chunk"; then
        echo "table"
        return
    fi

    if grep -Eq \
        '\\begin\{verbatim\}|\\begin\{lstlisting\}|\\begin\{minted\}' \
        "$chunk"; then
        echo "implementation"
        return
    fi

    # Subject categories.

    if grep -Eqi \
        'ontology|ontological|process-relational|structural realism|metaphysic' \
        <<<"$searchable"; then
        echo "ontology"
        return
    fi

    if grep -Eqi \
        'cosmolog|rsvp|scalar field|vector field|entropy|spacetime|gravity|physical law|field equation' \
        <<<"$searchable"; then
        echo "physics"
        return
    fi

    if grep -Eqi \
        'admissib|repair operator|continuation|reachability|constraint manifold|violation functional' \
        <<<"$searchable"; then
        echo "admissibility"
        return
    fi

    if grep -Eqi \
        'semantic|meaning|distinction|information|representation|language|beta reduction' \
        <<<"$searchable"; then
        echo "semantics"
        return
    fi

    if grep -Eqi \
        'biology|biological|physiology|homeostasis|immune|organism|metabolic' \
        <<<"$searchable"; then
        echo "biology"
        return
    fi

    if grep -Eqi \
        'artificial intelligence|language model|machine learning|neural|agent|llm' \
        <<<"$searchable"; then
        echo "ai"
        return
    fi

    if grep -Eqi \
        'econom|fiscal|market|capital|price|institution|governance' \
        <<<"$searchable"; then
        echo "economics"
        return
    fi

    if grep -Eqi \
        'rust|ownership|lifetime|compiler|programming language|runtime|algorithm' \
        <<<"$searchable"; then
        echo "computation"
        return
    fi

    if grep -Eqi \
        'example|case study|application|simulation|scenario' \
        <<<"$searchable"; then
        echo "application"
        return
    fi

    echo "exposition"
}

##############################################################################
# Commit message
##############################################################################

commit_message() {
    local type="$1"
    local category="$2"
    local title="$3"
    local clean

    clean="$(clean_title "$title")"

    case "$type" in
        part)
            printf '[part] Begin %s' "$clean"
            ;;

        chapter)
            printf '[chapter] Add %s' "$clean"
            ;;

        appendix)
            printf '[appendix] Begin appendices'
            ;;

        bibliography)
            printf '[bibliography] Add manuscript references'
            ;;

        *)
            printf '[%s][%s] Add %s' "$category" "$type" "$clean"
            ;;
    esac
}

##############################################################################
# Read and select index records
##############################################################################

declare -a UNIT_IDS=()
declare -a UNIT_TYPES=()
declare -a UNIT_TITLES=()
declare -a UNIT_STARTS=()
declare -a UNIT_ENDS=()

SOURCE_LINES="$(wc -l < "$SOURCE" | tr -d '[:space:]')"

while IFS=$'\t' read -r record_id record_type record_title record_line extra; do
    record_id="$(trim "${record_id:-}")"
    record_type="$(trim "${record_type:-}")"
    record_title="$(trim "${record_title:-}")"
    record_line="$(trim "${record_line:-}")"

    [[ -n "$record_id" ]] || continue
    [[ -n "$record_type" ]] || continue
    [[ "$record_line" =~ ^[0-9]+$ ]] || continue

    record_rank="$(rank_for_type "$record_type")"

    # Include all structural headings at or above the chosen granularity.
    #
    # With --level section, this includes:
    #
    #   part
    #   chapter
    #   section
    #   appendix
    #   bibliography
    #
    # It excludes subsection, theorem, definition, etc. Those remain inside
    # their containing section chunk.

    if ((record_rank <= LEVEL_RANK)); then
        UNIT_IDS+=("$record_id")
        UNIT_TYPES+=("$record_type")
        UNIT_TITLES+=("$record_title")
        UNIT_STARTS+=("$record_line")
    fi
done < "$INDEX"

UNIT_COUNT="${#UNIT_TYPES[@]}"

((UNIT_COUNT > 0)) || {
    echo "ERROR: No structural units found at level '$LEVEL'." >&2
    exit 1
}

for ((i = 0; i < UNIT_COUNT; i++)); do
    if ((i + 1 < UNIT_COUNT)); then
        UNIT_ENDS[i]=$((UNIT_STARTS[i + 1] - 1))
    else
        UNIT_ENDS[i]="$SOURCE_LINES"
    fi
done

FIRST_UNIT_START="${UNIT_STARTS[0]}"
PREAMBLE_END=$((FIRST_UNIT_START - 1))

##############################################################################
# Display plan
##############################################################################

say "============================================================"
say "Monotonic LaTeX Publication Pipeline"
say "============================================================"
say "Repository      : $(basename "$(pwd)")"
say "Source          : $SOURCE"
say "Index           : $INDEX"
say "Output          : $OUTPUT"
say "Granularity     : $LEVEL"
say "Structural units: $UNIT_COUNT"
say "Source lines    : $SOURCE_LINES"
say "Dry run         : $DRY_RUN"
say "Restart         : $RESTART"
say "Compile checks  : $COMPILE_CHECK"
say "Push at end     : $((1 - NO_PUSH))"

if [[ "$DRY_RUN" == "0" ]]; then
    say "Log             : $LOG"
    say "State           : $STATE_FILE"
fi

say "============================================================"

##############################################################################
# Restart handling
##############################################################################

if [[ "$RESTART" == "1" ]]; then
    if [[ "$DRY_RUN" == "1" ]]; then
        say
        say "DRY RUN: would remove:"
        say "  $OUTPUT"
        say "  $STATE_FILE"
    else
        rm -f -- "$OUTPUT" "$STATE_FILE"
        say
        say "Removed previous output and publishing state."
    fi
fi

##############################################################################
# Resume state
##############################################################################

completed=0

if [[ "$DRY_RUN" == "0" && -f "$STATE_FILE" ]]; then
    completed="$(cat "$STATE_FILE")"

    [[ "$completed" =~ ^[0-9]+$ ]] || {
        die "Invalid state file: $STATE_FILE"
    }

    ((completed <= UNIT_COUNT)) || {
        die "State file records more units than the current index contains."
    }

    [[ -f "$OUTPUT" ]] || {
        die "Publishing state exists, but $OUTPUT is missing. Use --restart."
    }
fi

if [[ "$DRY_RUN" == "1" && "$RESTART" == "0" && -f "$STATE_FILE" ]]; then
    completed="$(cat "$STATE_FILE" 2>/dev/null || echo 0)"

    if [[ ! "$completed" =~ ^[0-9]+$ ]]; then
        completed=0
    fi

    say
    say "Dry run will model resuming after $completed completed units."
fi

##############################################################################
# Ensure source and destination differ
##############################################################################

SOURCE_ABS="$(cd "$(dirname "$SOURCE")" && pwd)/$(basename "$SOURCE")"
OUTPUT_ABS="$(cd "$(dirname "$OUTPUT")" && pwd)/$(basename "$OUTPUT")"

[[ "$SOURCE_ABS" != "$OUTPUT_ABS" ]] || {
    die "Source and output paths must be different."
}

##############################################################################
# Initialize destination with preamble/front matter
##############################################################################

if [[ "$completed" == "0" ]]; then
    say
    say "------------------------------------------------------------"
    say "Initialization"
    say "------------------------------------------------------------"
    say "Copy source lines 1-$PREAMBLE_END"
    say "Destination: $OUTPUT"
    say "Commit: [structure] Initialize RSVP evolution manuscript"

    if [[ "$DRY_RUN" == "1" ]]; then
        say "DRY RUN: sed -n '1,${PREAMBLE_END}p' '$SOURCE' > '$OUTPUT'"
        say "DRY RUN: git add -- '$OUTPUT'"
        say "DRY RUN: git commit --only -m '[structure] Initialize RSVP evolution manuscript' -- '$OUTPUT'"
    else
        if ((PREAMBLE_END > 0)); then
            sed -n "1,${PREAMBLE_END}p" "$SOURCE" > "$OUTPUT"
        else
            : > "$OUTPUT"
        fi

        git add -- "$OUTPUT"

        if git diff --cached --quiet -- "$OUTPUT"; then
            die "Initialization did not stage any destination changes."
        fi

        git commit --only \
            -m "[structure] Initialize RSVP evolution manuscript" \
            -- "$OUTPUT" 2>&1 | tee -a "$LOG"

        printf '0\n' > "$STATE_FILE"
    fi
fi

##############################################################################
# Optional compile check
##############################################################################

compile_output() {
    local output_dir
    local output_name

    output_dir="$(dirname "$OUTPUT")"
    output_name="$(basename "$OUTPUT")"

    say "Compile check: $OUTPUT"

    (
        cd "$output_dir"
        lualatex \
            -interaction=nonstopmode \
            -halt-on-error \
            "$output_name"
    ) 2>&1 | tee -a "$LOG"
}

##############################################################################
# Publish units
##############################################################################

created=0

for ((i = completed; i < UNIT_COUNT; i++)); do
    number=$((i + 1))
    type="${UNIT_TYPES[i]}"
    title="${UNIT_TITLES[i]}"
    start="${UNIT_STARTS[i]}"
    end="${UNIT_ENDS[i]}"

    temp_chunk="$(mktemp)"

    cleanup_chunk() {
        rm -f -- "$temp_chunk"
    }

    trap cleanup_chunk RETURN

    sed -n "${start},${end}p" "$SOURCE" > "$temp_chunk"

    category="$(classify_chunk "$type" "$title" "$temp_chunk")"
    message="$(commit_message "$type" "$category" "$title")"
    display_title="$(clean_title "$title")"

    say
    say "------------------------------------------------------------"
    say "[$number/$UNIT_COUNT]"
    say "------------------------------------------------------------"
    say "Type       : $type"
    say "Category   : $category"
    say "Title      : $display_title"
    say "Source     : lines $start-$end"
    say "Destination: $OUTPUT"
    say "Commit     : $message"

    if [[ "$DRY_RUN" == "1" ]]; then
        say "DRY RUN: sed -n '${start},${end}p' '$SOURCE' >> '$OUTPUT'"
        say "DRY RUN: git add -- '$OUTPUT'"
        say "DRY RUN: git commit --only -m '$message' -- '$OUTPUT'"

        if [[ "$COMPILE_CHECK" == "1" ]]; then
            say "DRY RUN: lualatex -interaction=nonstopmode -halt-on-error '$OUTPUT'"
        fi
    else
        cat "$temp_chunk" >> "$OUTPUT"

        if [[ "$COMPILE_CHECK" == "1" ]]; then
            if ! compile_output; then
                say
                say "Compilation failed after adding:"
                say "  $message"
                say
                say "Restoring destination to the previous commit."

                git restore --staged --worktree -- "$OUTPUT"
                exit 1
            fi
        fi

        git add -- "$OUTPUT"

        if git diff --cached --quiet -- "$OUTPUT"; then
            say "No destination change detected; skipping commit."
        else
            git commit --only \
                -m "$message" \
                -- "$OUTPUT" 2>&1 | tee -a "$LOG"

            created=$((created + 1))
        fi

        printf '%s\n' "$number" > "$STATE_FILE"
    fi

    rm -f -- "$temp_chunk"
    trap - RETURN
done

##############################################################################
# Final verification
##############################################################################

say
say "============================================================"
say "Publication pass complete"
say "============================================================"

if [[ "$DRY_RUN" == "1" ]]; then
    planned=$((UNIT_COUNT - completed))

    say "Planned structural commits: $planned"
    say
    say "No files, commits, state, or remote branches were changed."

    if [[ "$NO_PUSH" == "0" ]]; then
        say "DRY RUN: git push"
    else
        say "Push disabled by --no-push."
    fi

    exit 0
fi

if ! cmp -s "$SOURCE" "$OUTPUT"; then
    say "ERROR: The reconstructed destination differs from the source."
    say
    say "Inspect with:"
    say "  diff -u '$SOURCE' '$OUTPUT'"
    say
    say "The script will not push."
    exit 1
fi

say "Verification     : destination exactly matches source"
say "Commits created  : $created"
say "Completed units  : $UNIT_COUNT/$UNIT_COUNT"

##############################################################################
# Push once
##############################################################################

if [[ "$NO_PUSH" == "1" ]]; then
    say "Push            : disabled"
else
    say "Push            : starting"

    git push 2>&1 | tee -a "$LOG"

    say "Push            : complete"
fi

##############################################################################
# Completion
##############################################################################

rm -f -- "$STATE_FILE"

say
say "Done."
say "Final file: $OUTPUT"
say "Log file  : $LOG"
